default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oscar_m_e_dashboard_development

test:
  <<: *default
  database: oscar_m_e_dashboard_test

staging:
  <<: *default
  database: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_NAME'] %>
  username: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_USERNAME'] %>
  password: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_NAME'] %>
  username: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_USERNAME'] %>
  password: <%= ENV['OSCAR_M_E_DASHBOARD_DATABASE_PASSWORD'] %>
